### ISSUE TITLE
Strong Name Signing

### ISSUE THREAD

**Issue by crohkohl** [kenkendk/sharpaescrypt#10]
Thank you for the great library! I am using the nuget-package in a ClickOnce application and have problems with deployment because the DLL is not signed with a strong name.

Could you do that for a next release?

**Comment by kenkendk** [comment]
No, I do not plan on doing so. 

The project is LGPL licensed and that means that the end users must be able to upgrade to a newer version of the library, even if the application using the library is not updated. My understanding of the LGPL is that this means the user must be able to re-compile the library and replace it, which can only be done if (a) the library is not signed, or (b) if the sign key is known.

If the sign key is known for any of the strong name libraries an application uses, the whole application has no protection from strong naming. Others agree that (b) is a bad move:
https://stackoverflow.com/questions/396143/net-opensource-projects-and-strong-named-assemblies

This leaves option (a) which is not using a strong name, as others agree on as well:
https://softwareengineering.stackexchange.com/a/345318

Had I written the library today, I would have used MIT licensing, but it is now LGPL for better or worse.

In my understanding of LGPL, If you only deploy the application internally you can simply re-sign the library: 
https://github.com/martinkirsche/StrongNameResigner

**Comment by crohkohl** [comment]
That is a good point. Did not consider that. Thank you for the tip!
