### ISSUE TITLE
Deployment error with ClickOnce

### ISSUE THREAD

**Issue by fosterz** [kenkendk/sharpaescrypt#13]
I'm using dll version of sharaescrypt in wpf application and getting below error while publishing it via ClickOnce application.

**Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\Published Apps\xyz\Tool\PrismUploadUI.application resulted in exception. Following failure messages were detected:
		+ Reference in the manifest does not match the identity of the downloaded assembly SharpAESCrypt.dll.**

**Comment by kenkendk** [comment]
I have not used ClickOnce in many years, but here are some suggestions for how to fix it:
https://stackoverflow.com/questions/5337458/error-deploying-clickonce-application-reference-in-the-manifest-does-not-match
